name: textbook

channels:
  - conda-forge

dependencies:
  - pip:
    - bs4
    - tqdm
    - numpy
    - pyyaml
    - nbformat
    - nbclean
    - pandas
    - scipy
    - sklearn
    - seaborn
    - sunpy
    - suds-jurko
    - astropy
    - drms
    - mpld3
    - matplotlib
    - mpld3
    - datetime
    - lime
    - torch
    - keras
    - jupyter_contrib_nbextensions
    - IPython
    - scipy
    - warnings
    - "--editable=git+https://github.com/i4Ds/IRISreader.git@ab6ecd9fafdcdb04e70f0b7b8cde7a1fc4ec55a0#egg=IRISreader"
