name: helioml_ch3

channels:
  - conda-forge

dependencies:
  - python=3.7
  - pip
  - pip:
    - jupyter
    - jupyterlab
    - jupyter_contrib_nbextensions
    - tqdm
    - numpy
    - scipy
    - sunpy
    - astropy
    - matplotlib
    - keras==2.2.4
    - tensorflow==1.13.1
    - h5py==2.10.0
# https://github.com/tensorflow/tensorflow/issues/44467